version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: bayes-engine-postgres
    environment:
      POSTGRES_USER: hyperdrive-user
      POSTGRES_PASSWORD: localdev_password
      POSTGRES_DB: neondb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hyperdrive-user"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
