name: Cleanup PR Preview

on:
  pull_request:
    types: [closed]

permissions:
  actions: read
  contents: read
  pull-requests: write

jobs:
  determine-runner:
    name: Determine Runner
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    outputs:
      runner: ${{ steps.set-runner.outputs.use-runner }}
    steps:
      - name: Determine which runner to use
        id: set-runner
        uses: jimmygchen/runner-fallback-action@v1
        with:
          primary-runner: "self-hosted,Linux,ARM64"
          fallback-runner: "ubuntu-24.04-arm"
          github-token: ${{ secrets.PAT }}

  cleanup:
    name: Delete PR Preview Deployment
    needs: determine-runner
    runs-on: ${{ fromJson(needs.determine-runner.outputs.runner) }}
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Delete preview deployment
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: delete --name bayes-engine-pr-${{ github.event.pull_request.number }}

      - name: Comment on PR
        uses: actions/github-script@v8
        with:
          script: |
            const prNumber = context.issue.number;
            const body = `### 🧹 PR Preview Cleaned Up\n\nThe preview deployment for this PR has been deleted.`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: body,
            });
