name: Cleanup PR Preview

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    name: Delete PR Preview Deployment
    runs-on: [self-hosted, Linux, ARM64]
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Delete preview deployment
        run: |
          . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
          wrangler delete --name bayes-engine-pr-${{ github.event.pull_request.number }} || true
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Comment on PR
        uses: actions/github-script@v8
        with:
          script: |
            const prNumber = context.issue.number;
            const body = `### 🧹 PR Preview Cleaned Up\n\nThe preview deployment for this PR has been deleted.`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: body,
            });
